language: fr

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: TEDPolicy
  max_history: 5
  epochs: 100
  nlu_threshold: 0.3
  core_threshold: 0.3
  fallback_action_name: "action_default_fallback"
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
assistant_id: 20250519-152827-inclusive-division

regex:
  - name: montant
    pattern: '[0-9]+ *€?|[0-9]+ *e(?:uros)?'