version: '3.7'

services:
  rasa:
    image: rasa/rasa:3.8.0-full
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command: 
      - run
      - --cors
      - "*"
      - --debug
      - --endpoints
      - endpoints.yml
    depends_on:
      - rasa-actions

  rasa-actions:
    image: rasa/rasa-sdk:3.8.0
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions